package ws.soap.service.random;

import javax.xml.ws.Binding;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.soap.SOAPFaultException;

import com.koitoer.jax.ws.soap.service.random.client.RandomService;
import com.koitoer.jax.ws.soap.service.random.client.RandomServicePortType;

public class RandServiceClient {

	public static void main(String args[]) throws Exception{

		// Using code generated by wsimport
		RandomService randomService = new RandomService();
		RandomServicePortType port = randomService.getRandomServicePort();

		Binding binding = ((BindingProvider) port).getBinding();

		System.out.println(binding.getHandlerChain());

		((BindingProvider) port).getRequestContext().put(
		        BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "http://localhost:8889/rs");

		System.out.println(((BindingProvider) port).getRequestContext().get(
		        BindingProvider.SOAPACTION_URI_PROPERTY));
		System.out.println(((BindingProvider) port).getRequestContext().get(
		        BindingProvider.SOAPACTION_USE_PROPERTY));
		System.out.println(((BindingProvider) port).getRequestContext().get(
		        BindingProvider.SESSION_MAINTAIN_PROPERTY));
		System.out.println(((BindingProvider) port).getRequestContext().get(
		        BindingProvider.PASSWORD_PROPERTY));
		System.out.println(((BindingProvider) port).getRequestContext().get(
		        BindingProvider.USERNAME_PROPERTY));

		System.out.println(((BindingProvider) port).getRequestContext());
		System.out.println(((BindingProvider) port).getResponseContext());

		System.out.println(((BindingProvider) port).getEndpointReference());

		try {
			System.out.println(port.next1());
		} catch (SOAPFaultException e) {
			System.out.println("SOAP FAULT > " + e.getFault().getFaultString());
			System.out.println(e.getMessage());
		}

	}
}
