
package ws.soap.echo.client.genAsync;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EchoServiceImplService", targetNamespace = "http://echo.soap.ws.jax.koitoer.com/", wsdlLocation = "http://localhost:9999/echo?wsdl")
public class EchoServiceImplService
    extends Service
{

    private final static URL ECHOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ECHOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ECHOSERVICEIMPLSERVICE_QNAME = new QName("http://echo.soap.ws.jax.koitoer.com/", "EchoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/echo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECHOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ECHOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EchoServiceImplService() {
        super(__getWsdlLocation(), ECHOSERVICEIMPLSERVICE_QNAME);
    }

    public EchoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECHOSERVICEIMPLSERVICE_QNAME, features);
    }

    public EchoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ECHOSERVICEIMPLSERVICE_QNAME);
    }

    public EchoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECHOSERVICEIMPLSERVICE_QNAME, features);
    }

    public EchoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "EchoServiceImplPort")
    public EchoService getEchoServiceImplPort() {
        return super.getPort(new QName("http://echo.soap.ws.jax.koitoer.com/", "EchoServiceImplPort"), EchoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "EchoServiceImplPort")
    public EchoService getEchoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://echo.soap.ws.jax.koitoer.com/", "EchoServiceImplPort"), EchoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECHOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ECHOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ECHOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
