
package ws.soap.server.service.tempConvert.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TempConvert", targetNamespace = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TempConvert {


    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod(operationName = "f2c")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "f2c", targetNamespace = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/", className = "com.koitoer.jax.ws.soap.server.service.tempConvert.client.F2C")
    @ResponseWrapper(localName = "f2cResponse", targetNamespace = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/", className = "com.koitoer.jax.ws.soap.server.service.tempConvert.client.F2CResponse")
    @Action(input = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/TempConvert/f2cRequest", output = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/TempConvert/f2cResponse")
    public float f2C(
        @WebParam(name = "arg0", targetNamespace = "")
            float arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod(operationName = "c2f")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "c2f", targetNamespace = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/", className = "com.koitoer.jax.ws.soap.server.service.tempConvert.client.C2F")
    @ResponseWrapper(localName = "c2fResponse", targetNamespace = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/", className = "com.koitoer.jax.ws.soap.server.service.tempConvert.client.C2FResponse")
    @Action(input = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/TempConvert/c2fRequest", output = "http://tempConvert.service.server.soap.ws.jax.koitoer.com/TempConvert/c2fResponse")
    public float c2F(
        @WebParam(name = "arg0", targetNamespace = "")
            float arg0);

}
