
package webservices.chapter5.soap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PredictionsSOAP", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PredictionsSOAP {


    /**
     * 
     * @return
     *     returns java.util.List<com.koitoer.webservices.chapter5.soap.client.Prediction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.GetAllResponse")
    @Action(input = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/getAllRequest", output = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/getAllResponse")
    public List<Prediction> getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.koitoer.webservices.chapter5.soap.client.Prediction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOne", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.GetOne")
    @ResponseWrapper(localName = "getOneResponse", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.GetOneResponse")
    @Action(input = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/getOneRequest", output = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/getOneResponse")
    public Prediction getOne(
        @WebParam(name = "arg0", targetNamespace = "")
            int arg0);

    /**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws VerbosityException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "edit", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.EditResponse")
    @Action(input = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/editRequest", output = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/editResponse", fault = {
        @FaultAction(className = VerbosityException_Exception.class, value = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/edit/Fault/VerbosityException")
    })
    public String edit(
        @WebParam(name = "arg0", targetNamespace = "")
            int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
            String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
            String arg2)
        throws VerbosityException_Exception
    ;

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.DeleteResponse")
    @Action(input = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/deleteRequest", output = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/deleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
            int arg0);

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws VerbosityException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://soaphandlers.chapter5.webservices.koitoer.com/", className = "com.koitoer.webservices.chapter5.soap.client.CreateResponse")
    @Action(input = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/createRequest", output = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/createResponse", fault = {
        @FaultAction(className = VerbosityException_Exception.class, value = "http://soaphandlers.chapter5.webservices.koitoer.com/PredictionsSOAP/create/Fault/VerbosityException")
    })
    public String create(
        @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
            String arg1)
        throws VerbosityException_Exception
    ;

}
