
package ws.soap.echo.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EchoService", targetNamespace = "http://echo.soap.ws.jax.koitoer.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://echo.soap.ws.jax.koitoer.com/", className = "com.koitoer.jax.ws.soap.echo.client.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://echo.soap.ws.jax.koitoer.com/", className = "com.koitoer.jax.ws.soap.echo.client.EchoResponse")
    @Action(input = "http://echo.soap.ws.jax.koitoer.com/EchoService/echoRequest", output = "http://echo.soap.ws.jax.koitoer.com/EchoService/echoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
