
package webservices.chapter5.clientMTOM;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SkiImageService", targetNamespace = "http://server.base64attach.chapter5.webservices.koitoer.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SkiImageService {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImage", targetNamespace = "http://server.base64attach.chapter5.webservices.koitoer.com/", className = "clientMTOM.GetImage")
    @ResponseWrapper(localName = "getImageResponse", targetNamespace = "http://server.base64attach.chapter5.webservices.koitoer.com/", className = "clientMTOM.GetImageResponse")
    public DataHandler getImage(
        @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<javax.activation.DataHandler>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImages", targetNamespace = "http://server.base64attach.chapter5.webservices.koitoer.com/", className = "clientMTOM.GetImages")
    @ResponseWrapper(localName = "getImagesResponse", targetNamespace = "http://server.base64attach.chapter5.webservices.koitoer.com/", className = "clientMTOM.GetImagesResponse")
    public List<DataHandler> getImages();

}
